#
# Project Makefile. Generic Drupal/Docker targets come from docker-base
# (docker/drupal.mk, updated by `make docker-update`); add project targets below.
#

include docker/drupal.mk

##@ Project

# my-target: ## What it does
# 	$(DRUSH) my:command

##@ Frontend (project-specific)

# install:: ## Install the Node dependencies
# 	$(EXEC_NODE) npm install
#
# npm-dev: ## Start the Vite dev server
# 	$(EXEC_NODE) npm run dev
#
# npm-build: ## Build the theme assets
# 	$(EXEC_NODE) npm run build
